### ISSUE TITLE
Add better support for smartphone

### ISSUE THREAD

**Issue by MadameMalady** [amit9838/weather#20]
Your weather app is looking great, and is usable with rotating the screen, however the ability to auto-adapt the ui is easy-enoooough with libadwaita and gtk4, it may require tweaking how the days are displayed, but would increase usabilty a lot! 
![aspectratioissue](https://github.com/amit9838/weather/assets/41642242/01adcbbc-2468-4198-8911-8892de1f02ec)

**Comment by amit9838** [comment]
Actually it was intended to target desktop initially, but now planning to add support for mobile too :slightly_smiling_face: .
But the problem is I don't have medium for test this view.
Is there any virtual simulator for mobile in your view?
btw thanks for you feedback :slightly_smiling_face:

**Comment by orowith2os** [comment]
> But the problem is I don't have medium to test mobile view like phone or simulator.

Just resize the window to a mobile-like size, that's the view libadwaita uses when on mobile devices.
