### ISSUE TITLE
Missing icons on KDE

### ISSUE THREAD

**Issue by MajliTech** [amit9838/weather#21]
Using Flatpak
![image](https://github.com/amit9838/weather/assets/68728886/c3b886c6-ffe6-4a0b-ac7f-de59952daa73)
on Fedora, KDE

**Comment by amit9838** [comment]
Have you installed this icons theme manually?

**Comment by MajliTech** [comment]
Which?

**Comment by ThechCorsair** [comment]
I have installed Adwaita, but nothing changed.

My OS:LMDE 6 (faye) x86_64 / Kernel: 6.1.0-13-amd64  / Icons: Adwaita++-Dark [GTK2/3]  / CPU: Intel i3-4160 (4) @ 3.600GHz

**Comment by amit9838** [comment]
can you pls varify whether you have installed correct Adwaita icons 
1.  Either use GTK Icon browser or check the file names from .icons directory
2. Match some icon names from here [icon names](https://github.com/amit9838/weather/blob/master/src/constants.py) from line :23 to 42

**Comment by amit9838** [comment]
also planning to port icons in next version. so this will fix the icon issue.
