### ISSUE TITLE
App opens slowly and claims no internet connection

### ISSUE THREAD

**Issue by wuqso** [amit9838/weather#22]
It looks to be a nice app and I installed it from flathub. Then the app opens slowly and claims no internet connection.
I'm using Gnome 44 on Fedora 39.

**Comment by amit9838** [comment]
How often do you face this?

**Comment by wuqso** [comment]
I face this each time I open the app.

**Comment by amit9838** [comment]
Can you check whether you are able to acces these domains..
https://www.google.com/
https://openweathermap.org/

**Comment by wuqso** [comment]
What domains?

**Comment by amit9838** [comment]
Ok gereat, Are you able to acces google with browser?

**Comment by wuqso** [comment]
No, I cannot. That's the problem.

**Comment by amit9838** [comment]
[io.github.amit9838.weather.zip](https://github.com/amit9838/weather/files/12066005/io.github.amit9838.weather.zip)

Here is a build with openweather domain, you can use is untill next release.
btw, Thanks for bringing this to attention.  :smile:

**Comment by wuqso** [comment]
I installed the build and the app works well. Thank you very much.

**Comment by amit9838** [comment]
#32

**Comment by wuqso** [comment]
Hi, Thank you for the wonderful app. I'm using version 1.0.1 and I find that the visibility is always 24.1 km for different days and different cities.




-----原始邮件-----
发件人:"Amit Chaudhary" ***@***.***>
发送时间:2023-07-17 12:14:14 (星期一)
收件人: amit9838/weather ***@***.***>
抄送: wuqso ***@***.***>, Author ***@***.***>
主题: Re: [amit9838/weather] App opens slowly and claims no internet connection (Issue #22)






io.github.amit9838.weather.zip

Here is a build with openweather domain, you can use is untill next release.
btw, Thanks for bringing this to attention. 😄
