### ISSUE TITLE
Change in preferences to Different measures not persistent

### ISSUE THREAD

**Issue by dcorkrey** [amit9838/weather#24]
I can go into preferences and add/change location, but when I select Imperial instead of metric, it always reverts to metric

**Comment by amit9838** [comment]
[Screencast from 2023-07-20 22-51-23.webm](https://github.com/amit9838/weather/assets/61614402/25042d85-a62a-4507-9614-73017695422d)


It is working for me.

**Comment by bulbman1946** [comment]
I have the same issue on an app installed today. Change to Imperial and it reverts to Metric. Nice looking but not useful in metric.

**Comment by amit9838** [comment]
seems like there is some compatibility issue with destro maybe.

**Comment by bulbman1946** [comment]
I uninstalled and reinstalled and that solved the metric/imperial issue. For some reason, I lost the weather images.

**Comment by amit9838** [comment]
you mean icons like, clouds, drops etc?

**Comment by bulbman1946** [comment]
![Screenshot at 2023-10-25 10-21-05](https://github.com/amit9838/weather/assets/75627030/83b730af-bf86-4356-936e-bb4396f6d9f1)

**Comment by amit9838** [comment]
This may help
https://github.com/amit9838/weather/issues/21

**Comment by bulbman1946** [comment]
Thanks for all your help. I'll wait for the next edition. I have the data and can p[ass on the decoration!
Regards,
Monte
    On Wednesday, October 25, 2023 at 12:02:00 PM EDT, Amit Chaudhary ***@***.***> wrote:  
 
 


This may help
#21

**Comment by joekm** [comment]
Just installed, also having same problem.  Cannot switch off of Metric.  Installed on EndeavourOS, running Hyprland, via AUR.

**Comment by amit9838** [comment]
#32
