### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by begin-theadventure** [amit9838/weather#26]
https://fungi.yuggoth.org/weather

**Comment by amit9838** [comment]
Can you elaborate the issue more clearly?

**Comment by begin-theadventure** [comment]
The application named `weather` already existed on Linux (with the 1.0 release being in 2006) and is packaged on ~4 distributions, as tracked by [Repology](https://repology.org/project/weather/versions).

**Comment by amit9838** [comment]
Actually , this package has been developed under flathub community with app id ```
io.github.com.amit9838.weather
``` and  title ```
Weather
``` 
According to **flathub** app is identified by app id which us unique in this case, and I didn't find any supporting document that we can't use duplicate title for any app.  

I hope it was helpful.

**Comment by amit9838** [comment]
Actually , this package has been developed under flathub community with app id ```
io.github.com.amit9838.weather
``` and  title ```
Weather
``` 
According to **flathub** app is identified by app id which us unique in this case, and I didn't find any supporting document that we can't use duplicate title for any app.  

I hope it was helpful.

**Comment by amit9838** [comment]
Actually , this package has been developed under flathub community with app id ```
io.github.com.amit9838.weather
``` and  title ```Weather``` .
According to **flathub** app is identified by app id which us unique in this case, and I didn't find any supporting document that we can't use duplicate title for any app.  

I hope it was helpful.

**Comment by begin-theadventure** [comment]
What about outside Flathub?
What should it be named if the original `weather` app is already packaged?

**Comment by amit9838** [comment]
If someone has trademarked the name `weather` then he/she may raise copyright issue and in this case it is not, because you may see each platform have diffrent weather app developed by diffrent developers, like apple store, play store, ubuntu store, kde store, microsoft store etc. 
So it is pointless to say that if somehave build weather app on play store then i can't build weather app on flathub.

**Comment by begin-theadventure** [comment]
I didn't inquire about the trademark nor stores that aren't available on Linux. My previous question pertained to a different matter. Nevertheless, thanks for your time.
