### ISSUE TITLE
EXPOSED API KEY

### ISSUE THREAD

**Issue by aandrew-me** [amit9838/weather#3]
Hey man its a nice project! However I saw that you are using an API key and its public. So anyone can use it and make thousands of requests costing you a lot of money.

**Comment by aandrew-me** [comment]
I want to talk privately about this with you. Whats the best way to message you?

**Comment by amit9838** [comment]
Sure, we can talk here amitchaudhary0539@gmail.com

**Comment by amit9838** [comment]
Solved  5d0285b1ef259b2cdf3e10b7d218d88f1098019f

**Comment by aandrew-me** [comment]
Ok that's better, so you are letting users use their own API keys right? 

However I think there is another way and that's why I mailed you

**Comment by amit9838** [comment]
> Ok that's better, so you are letting users use their own API keys right?
> 
> However I think there is another way and that's why I mailed you

I couldn't find you mail can you plaese resend or tell you mail?

**Comment by aandrew-me** [comment]
> > Ok that's better, so you are letting users use their own API keys right?
> > However I think there is another way and that's why I mailed you
> 
> I couldn't find your mail can you plaese resend or tell your mail?

Oh no, I sent another mail and my email is aandrew.me@proton.me
