### ISSUE TITLE
Noon is shown as 12:00 AM instead of  12:00 PM

### ISSUE THREAD

**Issue by diabloconqueso** [amit9838/weather#30]
In the "Today" forecast, noon is shown as 12:00 AM (midnight) instead of 12:00 PM (noon).

![image](https://github.com/amit9838/weather/assets/3771553/7df2de9c-0155-4930-88f3-b073eec73e84)

**Comment by amit9838** [comment]
Thanks for your feedback, will fix this in upcoming version.

**Comment by amit9838** [comment]
#32
